# temporary disabled Nightly checks due to
# https://github.com/rust-lang/rust/issues/79560
status = [
  "Dependency Check",
  "iOS Stable",
  "MacOS Stable",
  #"MacOS Nightly",
  "Android Stable",
  "Ubuntu Stable",
  #"Ubuntu Nightly",
  "Windows Stable",
  #"Windows Nightly",
]
